### ISSUE TITLE
Could not resolve dependency for excalibur@0.29.1

### ISSUE THREAD

**Issue by ymoreiratiti** [excaliburjs/dev-tools#10]
### Steps to Reproduce
1. npm install latest excalibur
2. npm install latest dev-tools

### Expected Result
Install dev-tools successfully

### Actual Result
The package shows incompatibility between versions.
```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: hello-world-game@1.0.0
npm ERR! Found: excalibur@0.29.1
npm ERR! node_modules/excalibur
npm ERR!   excalibur@"0.29.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer excalibur@"~0.28.1" from @excaliburjs/dev-tools@0.28.0
npm ERR! node_modules/@excaliburjs/dev-tools
npm ERR!   @excaliburjs/dev-tools@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Environment

- browsers and versions: N/A
- operating system: Ubuntu
- Excalibur versions: 0.29.1
- (anything else that may be relevant) 

### Current Workaround
`npm install --force` seems to force install, but when running on browser we received this message:
![image](https://github.com/excaliburjs/dev-tools/assets/5731429/df9d5ff6-b03f-46b2-a990-c3be14a9be2e)

**Comment by eonarheim** [comment]
Hi @ymoreiratiti apologies I need to update the repos and documentation.

We are focusing on the browser extension for debugging going forward

https://chromewebstore.google.com/detail/excalibur-dev-tools/dinddaeielhddflijbbcmpefamfffekc

Source code: https://github.com/excaliburjs/excalibur-extension/

**Comment by eonarheim** [comment]
@ymoreiratiti  I've updated the readme, let me know if you have any concerns but I'll archive this repo tomorrow to avoid future confusion
